// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaOrgInspector: typeof import('@vueuse/schema-org')['SchemaOrgInspector']
    SchemaOrgQuestion: typeof import('@vueuse/schema-org')['SchemaOrgQuestion']
    SchemaOrgWebPage: typeof import('@vueuse/schema-org')['SchemaOrgWebPage']
  }
}
