// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    BreadcrumbList: typeof import('./src/components/BreadcrumbList.vue')['default']
    BtnAction: typeof import('./src/components/Btn/BtnAction.vue')['default']
    BtnBasic: typeof import('./src/components/Btn/BtnBasic.vue')['default']
    BtnIcon: typeof import('./src/components/Btn/BtnIcon.vue')['default']
    Contributors: typeof import('./src/components/Contributors.vue')['default']
    FeaturesList: typeof import('./src/components/FeaturesList.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Links: typeof import('./src/components/Links.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaOrgInspector: typeof import('#vueuse/schema-org/runtime')['SchemaOrgInspector']
    SchemaOrgPerson: typeof import('#vueuse/schema-org/runtime')['SchemaOrgPerson']
    SchemaOrgWebPage: typeof import('#vueuse/schema-org/runtime')['SchemaOrgWebPage']
    SchemaOrgWebSite: typeof import('#vueuse/schema-org/runtime')['SchemaOrgWebSite']
    SponsorBanner: typeof import('./src/components/SponsorBanner.vue')['default']
  }
}
